### ISSUE TITLE
Compile Errors in QT Creator 4.7.1

### ISSUE THREAD

**Issue by SwyssX** [stefanbesler/QADS#1]
Hello Stefan,

first of all big thanks for making QADS :)
I try to compile it but I get a lot of Errors.
(we used QT Creator 4.7.1 QT 5.11.2 MSVC 2015 32 Bit Windows 10 actual Twincat3 installed)
I download your repository as a .zip and unzip it to a Directory.
I download your Beckhoff ADS git repository and copy the whole structure in your /ADS Directory.
I choose MSVC 2015 32Bit as build Enviroment.
Twincat is installed under C:/Twincat so the path to the ADS .dll .lib and .h files is correct.

When I do a fresh rebuild in QT creator I get a lot of compile Errors.

C:\TwinCAT\AdsApi\TcAdsDll\Include\TcAdsAPI.h:39: Fehler: 'AmsAddr' was not declared in this scope

Seems as if he does not correctly reference TcAdsDef.h?
Do I have to set any defines oder am I doing something wrong?

Big Thanks

Erik

**Comment by stefanbesler** [comment]
Hi Erik,

I just tried a fresh install from the repo and found (and then fixed) a small bug if you compile on windows - usually i compile on Linux.
The Beckhoff ADS git repository is in fact only required for Linux, you don't need it for Windows. Simply download the zip file or clone the repository and you are fine.
What compiler are you using? I am using MinGW 5.3.0 32bit and it compiles just fine.
TcAdsDef.h is located in the same directory as TcAdsAPI.h and is included by the later file - Just in case I modified the code in order to include TcAdsDef.h already in Tc3Manager.h

Can you try to download the repo again with the applied patched and in case of an error send the compiler output here?

Cheers,
Stefan

**Comment by SwyssX** [comment]
Hey StefanVielen Dank für Deine schnelle Antwort :)Ich bin übrigens der Bruder von Tobias Huber derMit Dir in Innsbruck auf der Physik gearbeitet hat.Lustig wie klein die Welt ist.Ich werds am Montag gleich testen.Wenns klappt steht ne Pizza :)Hier noch meine normale Email eh at swyss dot netViele GrüsseErikGesendet von meinem HUAWEI Smartphone.-------- Originalnachricht --------Betreff: Re: [stefanbesler/QADS] Compile Errors in QT Creator 4.7.1 (#1)Von: Stefan Besler An: stefanbesler/QADS Cc: Erik ,Author Hi Erik,
I just tried a fresh install from the repo and found (and then fixed) a small bug if you compile on windows - usually i compile on Linux.
The Beckhoff ADS git repository is in fact only required for Linux, you don't need it for Windows. Simply download the zip file or clone the repository and you are fine.
What compiler are you using? I am using MinGW 5.3.0 32bit and it compiles just fine.
TcAdsDef.h is located in the same directory as TcAdsAPI.h and is included by the later file - Just in case I modified the code in order to include TcAdsDef.h already in Tc3Manager.h
Can you try to download the repo again with the applied patched and in case of an error send the compiler output here?
Cheers,
Stefan

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/stefanbesler/QADS","title":"stefanbesler/QADS","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/stefanbesler/QADS"}},"updates":{"snippets":[{"icon":"PERSON","message":"@stefanbesler in #1: Hi Erik,\r\n\r\nI just tried a fresh install from the repo and found (and then fixed) a small bug if you compile on windows - usually i compile on Linux.\r\nThe Beckhoff ADS git repository is in fact only required for Linux, you don't need it for Windows. Simply download the zip file or clone the repository and you are fine.\r\nWhat compiler are you using? I am using MinGW 5.3.0 32bit and it compiles just fine.\r\nTcAdsDef.h is located in the same directory as TcAdsAPI.h and is included by the later file - Just in case I modified the code in order to include TcAdsDef.h already in Tc3Manager.h\r\n\r\nCan you try to download the repo again with the applied patched and in case of an error send the compiler output here?\r\n\r\nCheers,\r\nStefan"}],"action":{"name":"View Issue","url":"https://github.com/stefanbesler/QADS/issues/1#issuecomment-433534791"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/stefanbesler/QADS/issues/1#issuecomment-433534791",
"url": "https://github.com/stefanbesler/QADS/issues/1#issuecomment-433534791",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [stefanbesler/QADS] Compile Errors in QT Creator 4.7.1 (#1)",
"sections": [
{
"text": "",
"activityTitle": "**Stefan Besler**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@stefanbesler",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"stefanbesler/QADS\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"stefanbesler/QADS\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/stefanbesler/QADS/issues/1#issuecomment-433534791"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 399875659\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by stefanbesler** [comment]
Haha, dann schöne Grüße an Tobi 🙂

**Comment by SwyssX** [comment]
Hello Stefan,

I tried the new version but now I get 
C:\TwinCAT\AdsApi\TcAdsDll\Include\TcAdsAPI.h:146: Fehler: C2065: "BOOL": nichtdeklarierter Bezeichner

I tried adding #include <stdbool.h> before #include <TcAdsDef.h> but this does not really seem to help.
Do I Need to add some define in the TcAdsAPI.h?

Big Thanks & Have a nice weekend

**Comment by stefanbesler** [comment]
BOOL usually is simply defined in #include<cstddef>

#define BOOL int 
#define TRUE 1
#define FALSE 2

... this should be defined along the way... What compiler are you using, Clan you try with MinGW, which is shipped by qtcreator?

**Comment by SwyssX** [comment]
Hello Stefan,

I fixed the defines but under mingw 32 I also had to add


#include <TcAdsDef.h>

**Comment by stefanbesler** [comment]
Could you make a pull request or send the code you had to change, so I can merge it?
Cheers, Stefan

**Comment by SwyssX** [comment]
Hello Stefan

I inserted
#define BOOL int
#define TRUE 1
#define FALSE 2
to Line 24 in TcAdsAPI.h
(Guess this can be done more Beautiful :)

And I inserted
#include <TcAdsDef.h>
To line 36 in tc3value.h

It compiles fine and I also tested with Twincat it works perfect :)
Big big thanks.
Email me privately for pizza :)

**Comment by stefanbesler** [comment]
Ok thanks, I will merge your patch. I can not update the code in the twincat directory, but I am sure we can fix this by defining BOOL before including the file.
Cheers,
Stefan
