### ISSUE TITLE
String Bug

### ISSUE THREAD

**Issue by SwyssX** [stefanbesler/QADS#5]
Hello Stefan,

all I tested works perfect so far.
I just found one Little bug with Strings.

In the SPS we define:

`  mytest: STRING:='HELLO';
`
in Main.c we add
```
    PlcAnalogIo mytest(manager->value("MAIN.mytest", Tc3Manager::AutoType, Tc3Manager::NotificationType::Cycle, 100, 500), &data);
    context->setContextProperty("mytest", &mytest);
```
this leads to a Segfault Crash on Startup.
The Crash occurs in line 217 of tc3value.cpp

`>     QVariant v = QVariant(static_cast<int>(self->variantType_), static_cast<void*>(data));`

So somehow casting the string goes wrong.
It works if the PLC variable is defined as WSTRING
but for WSTRING we miss the conversion in the Tc3Manager::tc3VariantType method.

We are very close to perfection :)

Best Regards & Big Thanks for your excellent work

Erik

**Comment by stefanbesler** [comment]
Hi Erik!

Why are you using strings together with the PlcAnalogIo class? This class is intended for Numeric values, i.e. values coming from an EL1808.

You could either:
* Use plc.value("MAIN.mytest").value directly in your QML file (same as I do with MAIN.variable in my example or
* bind a Tc3Value to a context
```
 Tc3Value *mytest = manager->value("MAIN.mytest", Tc3Manager::AutoType, Tc3Manager::NotificationType::Cycle, 100, 1000), &data);
    context->setContextProperty("actualMotorSpeed", mytest);    
```

However, yes, you found a bug :-) i never used strings with notifications and strings have to be treated a little bit different than primitive types. I fixed it already.

Cheers, Stefan

**Comment by SwyssX** [comment]
Hello Stefan

sorry I abused PlcAnalogIo for a quick test as I thought it uses a Qvariant anyway ;)
Big thanks for Fixing the Error so fast :)
I tested to pass a numerical string to PlcAnalogIo now this works perfect!

Stefan->Beer++;

Best Regards & Big Thanks

Erik

**Comment by SwyssX** [comment]
Guess you mean:

    Tc3Value *mytest = manager->value("drive_MODL.mytest", Tc3Manager::AutoType, Tc3Manager::NotificationType::Cycle, 100, 1000);
       context->setContextProperty("mytest", mytest);

Now it works perfect!
Big big thanks
